services:
  db:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: et
    volumes:
      - data:/data/db

  backend:
    build:
      context: ./Backend
    container_name: et-backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      MONGO_URI: mongodb://root:pass@db:27017/et?authSource=admin

  frontend:
    build:
      context: ./Frontend
    container_name: et-frontend
    ports:
      - "80:80"
    environment:
      REACT_APP_API_URL: http://localhost:5000

volumes:
  data: